# Generated by Django 5.2.7 on 2025-10-15 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_plans', '0001_initial'),
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='membership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership_plans.membership_plan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(limit_choices_to={'role': 'member'}, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('GooglePay', 'Google Pay'), ('ApplePay', 'Apple Pay'), ('GCash', 'GCash'), ('GoTyme', 'GoTyme'), ('PayPal', 'PayPal'), ('Maya', 'Maya'), ('InstaPay', 'InstaPay'), ('Cash', 'Cash (Manual Payment)')], max_length=50),
        ),
    ]
