# Generated by Django 5.2.7 on 2025-11-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_staffuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Staff', 'Staff')], default='Staff', max_length=10),
        ),
    ]
