# Generated by Django 5.2.7 on 2025-11-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_staffuser_email_alter_staffuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
    ]
