# Generated by Django 5.2.8 on 2025-11-17 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_staffuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Only numbers are allowed for phone number.', regex='^\\d+$')]),
        ),
    ]
