# Generated by Django 5.2.8 on 2025-11-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboardstats_dashboard_d_date_891865_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardstats',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
