# Generated by Django 5.2.8 on 2025-11-17 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_alter_member_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='emergency_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only numbers are allowed for emergency phone.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only numbers are allowed for phone number.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7, null=True),
        ),
    ]
