# Generated by Django 5.2.8 on 2025-11-17 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_alter_paymentsummary_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveMemberSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, unique=True)),
                ('active_count', models.PositiveIntegerField(default=0, help_text='Number of members with active memberships on this date')),
                ('total_members', models.PositiveIntegerField(default=0, help_text='Total number of non-deleted members on this date')),
                ('new_members_today', models.PositiveIntegerField(default=0, help_text='New members registered on this date')),
                ('expired_today', models.PositiveIntegerField(default=0, help_text='Memberships that expired on this date')),
                ('total_revenue_today', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue collected on this date', max_digits=12)),
                ('check_ins_today', models.PositiveIntegerField(default=0, help_text='Total check-ins on this date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Active Member Snapshot',
                'verbose_name_plural': 'Active Member Snapshots',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='metrics_act_date_466537_idx'), models.Index(fields=['-date'], name='metrics_act_date_f2536b_idx')],
            },
        ),
    ]
